export const postObjectIdKeys = [
  '_id',
  'parentId',
  'categories',
  'tags',
  'components',
  'authorId',
  'lastAuthorId',
  'langId',
  'attributeId',
  'attributeTermId',
  'variationTermId',
  'variationTerms',
  'productId',
  'similarItems',
  'ltId',
  'gtId',
];
